apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genesis-avalon-daemon.fullname" . }}
  labels:
    app: {{ include "genesis-avalon-daemon.name" . }}
    chart: {{ include "genesis-avalon-daemon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ include "genesis-avalon-daemon.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "genesis-avalon-daemon.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ include "genesis-avalon-daemon.name" . }}
        args:
          - start
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: genesis-config
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
            