apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "couchbase.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn