---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genesis-avalon-gateway.fullname" . }}-active
  labels:
    app: {{ include "genesis-avalon-gateway.name" . }}
    chart: {{ include "genesis-avalon-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if and .Values.linkerd .Values.linkerd.enabled }}
  annotations:
    linkerd.io/inject: enabled
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "genesis-avalon-gateway.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genesis-avalon-gateway.fullname" . }}-preview
  labels:
    app: {{ include "genesis-avalon-gateway.name" . }}
    chart: {{ include "genesis-avalon-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "genesis-avalon-gateway.name" . }}
    release: {{ .Release.Name }}
