apiVersion: v2
name: observability
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: loki
    condition: loki.enabled
    repository: https://grafana.github.io/helm-charts
    version: "5.43.3"
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: "7.3.3"
    condition: grafana.enabled
  - name: promtail
    repository: https://grafana.github.io/helm-charts
    version: "6.15.5"
    condition: promtail.enabled