loki:
  enabled: true
  loki:
    auth_enabled: false
    backend:
      affinity: ""
    commonConfig:
      replication_factor: 1
    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      type: s3
      s3:
        endpoint: https://assets.boltcutter.network
        region: eu-west-1
        secretAccessKey: qvBAftD07OTdx6FFis7gm7Bw3juvVQIL7vdyXf0P
        accessKeyId: tRD2lE9W7JOGyHmuc5ac
        s3ForcePathStyle: true
        insecure: false
    limits_config:
      enforce_metric_name: false
      max_entries_limit_per_query: 5000
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_query_series: 100000
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 16
      per_stream_rate_limit: 1MB
  test:
    enabled: false
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  singleBinary:
    replicas: 1
  monitoring:
    dashboards:
      enabled: false
    rules:
      enabled: false
    serviceMonitor:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false


grafana:
  enabled: true
  grafana.ini:
    server:
      root_url: "https://metrics.game.avalon.cool"
  persistence:
    enabled: true
  sidecar:
    imagePullPolicy: Always
  podAnnotations: {}
  annotations: {}
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "cluster-letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
    labels: {}
    path: /
    pathType: Prefix
    hosts:
      - metrics.game.avalon.cool
    tls:
      - hosts:
          - metrics.game.avalon.cool
        secretName: grafana-tls

promtail:
  enabled: true
  config:
    snippets:
      pipelineStages:
        - match:
            selector: '{namespace!="genesis-avalon-dev"}'
            action: drop
            drop_counter_reason: namespace
        # - match:
        #     selector: '{app="avalond"} |~ "http://[0-9\\.:]+/healthz"'
        #     action: drop
        #     drop_counter_reason: "healthcheck"
        # - match:
        #     selector: '{app="avalond"} |~ "request_path=/healthz"'
        #     action: drop
        #     drop_counter_reason: healthcheck
        - timestamp:
            source: time
            format: "2006-01-02T15:04:05.000Z"
            fallback_formats:
              - RFC3339